package inheritance;
class parentcons3{
	parentcons3(){
		//super(); executed by compiler object class constructor executed
		System.out.println("Parent class 0-arg constructor");
	}
}

public class inheritanceEx10 extends parentcons3 {
	inheritanceEx10(){
		//super(); code is generated by compiler
		System.out.println("Child class 0-arg constructor");
	}
	

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		new inheritanceEx10();
		
	}

}
